add code for check_not_valid_constraints.sql
mfvanek/pg-index-health pull request #374
Opened 2024-04-27 14:36 UTC by BLoHny

2024-04-27 14:36 UTC, BLoHny commented
The current test code doesn't seem to be good code.
Could you help me?

2024-04-27 15:31 UTC, mfvanek requested changes
There are checkstyle issues (see tests results).  
Please ensure that project builds locally: `./gradlew build`  
See https://github.com/mfvanek/pg-index-health/blob/master/CONTRIBUTING.md

2024-04-27 15:31 UTC, mfvanek commented on pg-index-health/src/main/java/io/github/mfvanek/pg/common/maintenance/Diagnostic.java
> +    CHECK_NOT_VALID_CONSTRAINTS(ExecutionTopology.ON_PRIMARY, "check_not_valid_constraints.sql", QueryExecutors::executeQueryWithSchema);
I'd prefer just `NOT_VALID_CONSTRAINTS` here

2024-04-27 15:31 UTC, mfvanek commented on pg-index-health/src/main/java/io/github/mfvanek/pg/checks/host/CheckNotValidConstraintsOnHost.java
> +public class CheckNotValidConstraintsOnHost extends AbstractCheckOnHost<ForeignKey> {
Let's rename it to `NotValidConstraintsCheckOnHost`

2024-04-27 15:31 UTC, mfvanek commented on pg-index-health/src/main/java/io/github/mfvanek/pg/checks/cluster/CheckNotValidConstraintsOnCluster.java
> +public class CheckNotValidConstraintsOnCluster extends AbstractCheckOnCluster<ForeignKey> {
Let's rename it to `NotValidConstraintsCheckOnCluster`

2024-04-27 15:31 UTC, mfvanek commented on pg-index-health/src/test/java/io/github/mfvanek/pg/checks/cluster/CheckNotValidConstraintsOnClusterTest.java
> +public class CheckNotValidConstraintsOnClusterTest extends DatabaseAwareTestBase {
Please rename test class the same as corresponding check-class

2024-04-27 15:31 UTC, mfvanek commented on pg-index-health/src/test/java/io/github/mfvanek/pg/checks/host/CheckNotValidConstraintsOnHostTest.java
> +public class CheckNotValidConstraintsOnHostTest extends DatabaseAwareTestBase {
Please rename test class the same as corresponding check-class

2024-04-27 16:30 UTC, mfvanek commented
> The current test code doesn't seem to be good code. Could you help me?

1. You can copy and modify existing class https://github.com/mfvanek/pg-index-health/blob/master/pg-index-health/src/test/java/io/github/mfvanek/pg/support/statements/AddLinksBetweenAccountsAndClientsStatement.java in order to bring not valid FK.
2. You can add one more column to https://github.com/mfvanek/pg-index-health/blob/master/pg-index-health/src/test/java/io/github/mfvanek/pg/support/statements/CreateTableWithCheckConstraintOnSerialPrimaryKey.java and not valid check constraint on it

2024-04-27 16:35 UTC, mfvanek commented on pg-index-health/src/main/java/io/github/mfvanek/pg/checks/host/CheckNotValidConstraintsOnHost.java
> +        super(ForeignKey.class, pgConnection, Diagnostic.CHECK_NOT_VALID_CONSTRAINTS);
Please take a look at my comment https://github.com/mfvanek/pg-index-health/issues/362#issuecomment-2044247293

I think we need a new `Constraint `class in model

2024-04-27 16:45 UTC, mfvanek commented on pg-index-health/src/main/java/io/github/mfvanek/pg/checks/host/CheckNotValidConstraintsOnHost.java
> +        super(ForeignKey.class, pgConnection, Diagnostic.CHECK_NOT_VALID_CONSTRAINTS);
```java
package io.github.mfvanek.pg.model.constraint;

import javax.annotation.Nonnull;
import java.util.Objects;

public enum ConstraintType {

    CHECK("c"),
    FOREIGN_KEY("f");

    // See https://www.postgresql.org/docs/current/catalog-pg-constraint.html
    private final String pgConType;

    ConstraintType(@Nonnull final String pgConType) {
        this.pgConType = Objects.requireNonNull(pgConType, "pgConType");
    }
}
```

and
```java
package io.github.mfvanek.pg.model.constraint;

import io.github.mfvanek.pg.model.DbObject;
import io.github.mfvanek.pg.model.table.TableNameAware;

import javax.annotation.concurrent.Immutable;

@Immutable
public class Constraint implements DbObject, TableNameAware {

    private final String tableName;
    private final String constraintName;
    private final ConstraintType constraintType;
    
    ...
}
```

2024-04-27 20:06 UTC, mfvanek commented on pg-index-health/src/main/java/io/github/mfvanek/pg/checks/host/CheckNotValidConstraintsOnHost.java
> +        super(ForeignKey.class, pgConnection, Diagnostic.CHECK_NOT_VALID_CONSTRAINTS);
For example see `IndexWithColumns` in https://github.com/mfvanek/pg-index-health/pull/377

2024-04-29 02:38 UTC, BLoHny commented
> > The current test code doesn't seem to be good code. Could you help me?
> 
> 1. You can copy and modify existing class https://github.com/mfvanek/pg-index-health/blob/master/pg-index-health/src/test/java/io/github/mfvanek/pg/support/statements/AddLinksBetweenAccountsAndClientsStatement.java in order to bring not valid FK.
> 2. You can add one more column to https://github.com/mfvanek/pg-index-health/blob/master/pg-index-health/src/test/java/io/github/mfvanek/pg/support/statements/CreateTableWithCheckConstraintOnSerialPrimaryKey.java and not valid check constraint on it

```java
// AddInvalidForeignKeyStatement.java
    @Override
    public void execute(@Nonnull final Statement statement) throws SQLException {
        statement.execute(String.format("alter table if exists %1$s.accounts " +
                        "add constraint c_accounts_fk_invalid foreign key (invalid_client_id) references %1$s.invalid_clients (invalid_id);",
                schemaName));
    }
```

```java
// CreateTableWithCheckConstraintOnSerialPrimaryKey.java
    @Override
    public void execute(@Nonnull final Statement statement) throws SQLException {
        statement.execute(String.format("create table if not exists %1$s.another_table(" +
                        "id bigserial primary key, " +
                        "invalid_column integer, " +
                        "constraint not_reserved_id check (id > 1000), " +
                        "constraint less_than_million check (id < 1000000), " +
                        "constraint always_false check (invalid_column > 100 AND invalid_column < 0));",
                schemaName));
    }
```

Is this modified code suitable?

2024-04-29 06:17 UTC, mfvanek commented
> Is this modified code suitable?

Unfortunately, no, it isn't.

When I say "not valid constraint" it's not about true or false constraint is, it's about whether database uses this constraint or not. Not valid constraint is like a draft. Please take a look at the original article https://habr.com/ru/articles/800121/

It should be like this
```
alter table if exists %1$s.accounts add constraint c_accounts_fk_client_id_not_validated_yet foreign key (client_id) references %1$s.clients (id) not valid;
```

In tests after you find all not valid constraints you can can call `validate constraint` and recheck the database: all issues should go away

2024-04-30 02:46 UTC, BLoHny commented
```java
    @ParameterizedTest
    @ValueSource(strings = {PgContext.DEFAULT_SCHEMA_NAME, "custom"})
    void onDatabaseWithNotValidatedForeignKey(final String schemaName) {
        executeTestOnDatabase(schemaName, DatabasePopulator::withInvalidForeignKey, ctx ->
                assertThat(check)
                        .executing(ctx)
                        .hasSize(1)
                        .containsExactlyInAnyOrder(
                                Constraint.of(ctx.enrichWithSchema("accounts"), "c_accounts_fk_client_id_not_validated_yet",
                                        ConstraintType.FOREIGN_KEY)
                        )
        );
    }
```
    
Is it okay to proceed with the test code like this?

2024-04-30 06:23 UTC, mfvanek commented
Hi @BLoHny 

> Is it okay to proceed with the test code like this?

I'd suggest a few enhancements:

1. Rename `withInvalidForeignKey` to `withNotValidConstraints`
2. Add not valid FK and not valid check constraint
3. Add `dbp -> dbp.withNotValidConstraints().withUniqueConstraintOnSerialColumn()` to ensure that sql query ignores unique constraints and PK's

2024-04-30 07:50 UTC, BLoHny commented
```sql
        statement.execute(String.format("alter table if exists %1$s.accounts " +
                        "add constraint c_accounts_chk_client_id_not_validated_yet check (client_id > 0) not valid;",
                schemaName));
```
After add more sql query..
```java
                        .containsExactly(
                                Constraint.of(ctx.enrichWithSchema("accounts"), "c_accounts_chk_client_id_not_validated_yet",
                                        ConstraintType.CHECK),
                                Constraint.of(ctx.enrichWithSchema("accounts"), "c_accounts_fk_client_id_not_validated_yet",
                                        ConstraintType.FOREIGN_KEY)
                        )
```

add test code

proceed like this?

2024-04-30 08:00 UTC, mfvanek commented
> proceed like this?

Yes, looks good

2024-04-30 08:25 UTC, closed without merging

2024-04-30 09:02 UTC, BLoHny commented
open new pull request https://github.com/mfvanek/pg-index-health/pull/382 by conflict