Add check for primary keys with serial types
mfvanek/pg-index-health pull request #421
Opened 2024-06-17 20:52 UTC by mfaulther

Relates to https://github.com/mfvanek/pg-index-health/issues/317

2024-06-18 14:00 UTC, mfvanek requested changes
Great job! It needs a little polish

2024-06-18 14:00 UTC, mfvanek commented on README.md
> +| 20 | Primary keys with [serial types](https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_serial)                                | static             | [sql](ttps://github.com/mfvanek/pg-ind
Broken link. See ` [sql](ttps:`

2024-06-18 14:00 UTC, mfvanek commented on spring-boot-integration/pg-index-health-test-starter/src/main/java/io/github/mfvanek/pg/spring/DatabaseStructureHealthAutoConfiguration.java
> +
Redundant empty line

2024-06-18 15:08 UTC, mfvanek commented
Relates to https://github.com/mfvanek/pg-index-health/issues/317

2024-06-18 18:16 UTC, mfaulther commented on spring-boot-integration/pg-index-health-test-starter/src/main/java/io/github/mfvanek/pg/spring/DatabaseStructureHealthAutoConfiguration.java
> +
Fixed

2024-06-19 05:58 UTC, mfvanek approved these changes

2024-06-19 06:09 UTC, merged